warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: warehouse_user
      pass: warehouse_pass
      dbname: analytics_warehouse
      schema: public
      threads: 4
