version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: raw_orders
        identifier: orders
      - name: raw_customers
        identifier: customers
      - name: raw_reviews
        identifier: product_reviews

models:
  - name: stg_orders
    description: "Staged orders with standardized status and time columns"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: total_amount
        tests:
          - not_null

  - name: stg_customers
    description: "Staged customers with cleaned email and computed account age"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - unique
          - not_null

  - name: stg_products
    description: "Staged products aggregated from review data"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_reviews
    description: "Staged reviews with sentiment categories"
    columns:
      - name: review_id
        tests:
          - unique
          - not_null
      - name: rating
        tests:
          - not_null

  - name: dim_customers
    description: "Customer dimension with surrogate keys"
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_products
    description: "Product dimension with review aggregates"
    columns:
      - name: product_key
        tests:
          - unique
          - not_null
      - name: product_id
        tests:
          - unique
          - not_null

  - name: fact_orders
    description: "Order fact table with resolved surrogate keys"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: fact_daily_sales
    description: "Aggregated daily sales per product"
    columns:
      - name: total_revenue
        tests:
          - not_null
      - name: total_orders
        tests:
          - not_null
